baseurl = "https://hugcis.github.io/hugo-astatine-theme/"
languageCode = "en-us"
title = "Astatine Theme"
theme = "hugo-astatine-theme"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"


[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[params]
    description = "The homepage of Astatine"
    authorName = "Jack Harkness"
    [params.imgname]
        name = "img/main.jpg"
        alt = "Profile picture"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"


[sitemap]
  filename = "sitemap.xml"
